---
name: Mirror to GitHub
on:
  push:
    branches:
      - master

jobs:
  main:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/mfinelli/pgbackup:latest
      - uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mfinelli/pgbackup
          short-description: "postgres + google-cloud-sdk for running backups"
